version: 2

defaults: &defaults
  working_directory: ~/project
  docker:
    - image: circleci/node:latest
  environment:
    NODE_ENV: test

jobs:
  setup:
    <<: *defaults
    steps:
      # Checkout repository
      - checkout

      # Restore cache
      - restore_cache:
          key: yarn-{{ checksum "yarn.lock" }}

      # Install dependencies
      - run:
          name: Install Dependencies
          command: NODE_ENV=dev yarn

      # Keep cache
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"

      # Persist workspace
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules

  lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Lint
          command: yarn lint

  audit:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Security Audit
          command: yarn audit --groups dependencies

  test-unit:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Unit Tests
          command: yarn test:unit --coverage && yarn coverage

  test-e2e-firefox:
    docker:
        - image: circleci/node:latest-browsers
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: E2E Tests
          command: yarn test:e2e --coverage && yarn coverage
          environment:
            BROWSER_STRING: firefox

  test-e2e-chrome:
    docker:
        - image: circleci/node:latest-browsers
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: E2E Tests
          command: yarn test:e2e --coverage && yarn coverage
          environment:
            BROWSER_STRING: chrome/selenium

  test-e2e-browserstack:
    docker:
        - image: circleci/node:latest-browsers
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: E2E Tests
          command: yarn test:e2e --coverage && yarn coverage
          environment:
            BROWSER_STRING: chrome/browserstack/local

  test-e2e-jsdom:
    docker:
        - image: circleci/node
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: E2E Tests
          command: yarn test:e2e --coverage && yarn coverage
          environment:
            BROWSER_STRING: jsdom

workflows:
  version: 2

  commit:
    jobs:
      - setup
      - lint:                   { requires: [setup] }
      - audit:                  { requires: [setup] }
      - test-unit:              { requires: [lint] }
      - test-e2e-firefox:       { requires: [lint] }
      - test-e2e-chrome:        { requires: [lint] }
      - test-e2e-browserstack:  { requires: [lint] }
      - test-e2e-jsdom:  { requires: [lint] }
