#!/usr/bin/env bash

BASE=`dirname $0`
JS_FILE="$BASE/../src/dependencies.js"

CONTENT="/**
 * THIS FILE IS AUTOMATICALLY GENERATED
 * DONT CHANGE ANYTHING MANUALLY
 */

export const dependencies = {"

for d in `grep -ir loadDependency\(\' src | cut -d\' -f2 | sort | uniq`; do
  CONTENT="$CONTENT
  '$d': () => import('$d'),"  >> $JS_FILE
done

CONTENT="${CONTENT:0:${#CONTENT}-1}
}"

echo "$CONTENT" > $JS_FILE
