/**
 * THIS FILE IS AUTOMATICALLY GENERATED
 * DONT CHANGE ANYTHING MANUALLY
 */

const _interopDefault = i => i.then(m => m.default || m)

export const browsers = {
  'browserstack': () => _interopDefault(import('./browserstack')),
  'browserstack/local': () => _interopDefault(import('./browserstack/local')),
  'chrome': () => _interopDefault(import('./chrome')),
  'chrome/browserstack': () => _interopDefault(import('./chrome/browserstack')),
  'chrome/browserstack/local': () => _interopDefault(import('./chrome/browserstack/local')),
  'chrome/puppeteer': () => _interopDefault(import('./chrome/puppeteer')),
  'chrome/selenium': () => _interopDefault(import('./chrome/selenium')),
  'edge': () => _interopDefault(import('./edge')),
  'edge/browserstack': () => _interopDefault(import('./edge/browserstack')),
  'edge/browserstack/local': () => _interopDefault(import('./edge/browserstack/local')),
  'edge/selenium': () => _interopDefault(import('./edge/selenium')),
  'firefox': () => _interopDefault(import('./firefox')),
  'firefox/browserstack': () => _interopDefault(import('./firefox/browserstack')),
  'firefox/browserstack/local': () => _interopDefault(import('./firefox/browserstack/local')),
  'firefox/selenium': () => _interopDefault(import('./firefox/selenium')),
  'ie': () => _interopDefault(import('./ie')),
  'ie/browserstack': () => _interopDefault(import('./ie/browserstack')),
  'ie/browserstack/local': () => _interopDefault(import('./ie/browserstack/local')),
  'ie/selenium': () => _interopDefault(import('./ie/selenium')),
  'puppeteer': () => _interopDefault(import('./puppeteer')),
  'puppeteer/core': () => _interopDefault(import('./puppeteer/core')),
  'safari': () => _interopDefault(import('./safari')),
  'safari/browserstack': () => _interopDefault(import('./safari/browserstack')),
  'safari/browserstack/local': () => _interopDefault(import('./safari/browserstack/local')),
  'safari/selenium': () => _interopDefault(import('./safari/selenium')),
  'saucelabs': () => _interopDefault(import('./saucelabs')),
  'selenium': () => _interopDefault(import('./selenium'))
}
